// The IndexNow submission list must not name pages that do not exist.
//
// THE DEFECT THIS ENCODES. PR #7 deleted three third-party pages. The hardcoded
// STATIC_URLS list in scripts/generate_site.py kept naming them, so every
// deploy regenerated _data/indexnow.json containing them and re-submitted them
// to Bing. Because the site answers 200 with the homepage for every unknown
// path, they looked alive from the outside, and the cleanup was being undone by
// the deploy on every run for three weeks.
//
// Removing the three entries fixes the symptom. This test fixes the class: a
// path in the submission list that has no page behind it fails CI.
//
// When generate_site.py is deleted and the submission list is derived from the
// sitemap, this test should be repointed at that, not dropped. A derived list
// makes the defect unlikely; it does not make it impossible.

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");

function staticUrls(): string[] {
  const py = readFileSync(join(ROOT, "scripts", "generate_site.py"), "utf8");
  const block = py.match(/STATIC_URLS = \[([\s\S]*?)\n\]/);
  expect(block, "STATIC_URLS not found in generate_site.py").not.toBeNull();
  return [...block![1]!.matchAll(/"([^"]+)"/g)].map((m) => m[1]!);
}

/** Where a published path comes from in the source tree, if anywhere. */
function sourceExists(path: string): boolean {
  if (path === "/") return existsSync(join(ROOT, "index.html"));
  const bare = path.replace(/^\//, "").replace(/\/$/, "");
  // A root file such as /llms.txt or /robots.txt.
  if (existsSync(join(ROOT, bare))) return true;
  // A directory page, Jekyll style.
  if (existsSync(join(ROOT, bare, "index.html"))) return true;
  // An Astro page already built.
  if (existsSync(join(ROOT, "dist", bare, "index.html"))) return true;
  // Generated by jekyll-sitemap rather than committed.
  if (bare === "sitemap.xml") return true;
  return false;
}

describe("the IndexNow submission list", () => {
  const urls = staticUrls();

  it("is not empty, so this suite cannot pass vacuously", () => {
    expect(urls.length).toBeGreaterThan(0);
  });

  it("names only paths that have a page behind them", () => {
    const orphans = urls.filter((u) => !sourceExists(u));
    expect(orphans, `submission list names paths with no source: ${orphans.join(", ")}`).toEqual([]);
  });

  it("no longer names the three pages deleted in #7", () => {
    for (const dead of ["/joe-prich/", "/rob-hein/", "/prichards-air-conditioning-neo-nazi/"]) {
      expect(urls, `${dead} is deleted and must not be submitted`).not.toContain(dead);
    }
  });

  it("still names /retractions/rob-hein/, which is a live page", () => {
    // Guards a real mistake made while fixing this: a suffix match on
    // "/rob-hein/" also matches "/retractions/rob-hein/", so a careless filter
    // removes a page that exists. The URL counts did not add up, which is how
    // it was caught.
    expect(urls).toContain("/retractions/rob-hein/");
  });
});
